### ISSUE TITLE
The feature for ProbCover

### ISSUE THREAD

**Issue by ZiTingW** [avihu111/TypiClust#3]
Which features are used to select new samples in the ProbCover, the features obtained in the previous active learning round or self-supervised features based on SimCLR?

**Comment by avihu111** [comment]
Thanks for your question. 

In this implementation and in the main experiments in the paper, we use the features **obtained from SimCLR**.
In low budgets, the features from the previous AL round can be biased due to the small training set.
In the experiment shown in Figure 10, we provide an ablation using ProbCover with the previous round features. 

I'm closing this issue. Feel free to reopen it if you have additional questions.

**Comment by ZiTingW** [comment]
Thank you for your kind reply!
